### ISSUE TITLE
Engine Version suggestion

### ISSUE THREAD

**Issue by linshun** [synergie7/cocos2d-HTML5-traffic-control#1]
I suggest you to have a Cocos2d-html5 submodule on this game.
It will keep the right version which runs well with your game. The version on Github is always under developing or unstable.

**Comment by synergie7** [comment]
Thanks. 

I"m not sure how to do that.

I'll need to read the github documentation.

EDIT. 
I'm currently doing this....

**Comment by synergie7** [comment]
Done.

@linshun , Please check it works for you and I'll close the issue if its OK.

Cheers

Roger Clark

**Comment by synergie7** [comment]
I've tested this by downloading the project master zip and then clicked on the Cocos2d-html5 subproject (reference number) and downloaded that, renamed the sub project to be the correct name (cocos2d-html5) and tested, and it works fine.
